### INPUT PARAMETERS ###

# paths to fastq files, should be key: value pairs as key will be used as sample name 

fastq_fns: 
  20191112_human_bham1: workman_Bham_Run1_20171120_cDNA/raw_data/Bham_Run1_20171120_1D2_1Donly.all.dedeup.fastq
  20191112_human_bham2: workman_Bham_Run2_20171120_cDNA/raw_data/Bham_Run2_20171120_1D2_1Donly.all.dedeup.fastq
  20191112_human_hopkins1: workman_Hopkins_Run1_20171011_cDNA/raw_data/Hopkins_Run1_20171011_1D2_1Donly.all.dedeup.fastq
  20191112_human_hopkins2: workman_Hopkins_Run2_20171011_cDNA/raw_data/Hopkins_Run2_20171011_1D2_1Donly.all.dedeup.fastq

# directories to put outputs for each sample into

basedirs: 
  20191112_human_bham1: workman_Bham_Run1_20171120_cDNA
  20191112_human_bham2: workman_Bham_Run2_20171120_cDNA
  20191112_human_hopkins1: workman_Hopkins_Run1_20171011_cDNA
  20191112_human_hopkins2: workman_Hopkins_Run2_20171011_cDNA

sequencing_type: cdna

### REFERENCE PARAMETERS ###

genome_fasta_fn: /cluster/ggs_lab/mtparker/annotations/GRCh38/fasta/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa
chromsizes_fn: /cluster/ggs_lab/mtparker/annotations/GRCh38/fasta/Homo_sapiens.GRCh38.dna_sm.primary_assembly.chrom.sizes
transcriptome_fasta_fn: /cluster/ggs_lab/mtparker/annotations/GRCh38/fasta/Homo_sapiens.GRCh38.cdna.all.fa
annot_gtf: /cluster/ggs_lab/mtparker/annotations/GRCh38/gtf/Homo_sapiens.GRCh38.98.gtf
is_ensembl: True

### SIMULATEION PARAMETERS ###

yanosim_parameters:
  threads: 24
  random_seed: 101
  run_simulation: False

### MAPPING PARAMETERS ###

minimap2_parameters:
  threads: 24
  max_intron_size: 200000
  junction_bonus: 12

### FILTERING PARAMETERS ###

2passtools_parameters:
  threads: 12
  jad_size_threshold: 4
  primary_junction_search_distance: 20
  canonical_motifs: 'GTAG|GCAG|ATAG'
  sequence_model_window_size: 128
  sequence_model_kfold: 6
  low_confidence_threshold: 0.1
  high_confidence_threshold: 0.6


### ASSEMBLY PARAMETERS ###

stringtie_parameters:
  threads: 24