### INPUT PARAMETERS ###

# paths to fastq files, should be key: value pairs as key will be used as sample name 

fastq_fns: 
  isoseq_brain_fulllength: isoseq_human_brain_fulllength/raw_data/brain.flnc.fasta
  isoseq_brain_notfulllength: isoseq_human_brain_notfulllength/raw_data/brain.nfl.fasta
  isoseq_liver_fulllength: isoseq_human_liver_fulllength/raw_data/liver.flnc.fasta
  isoseq_liver_notfulllength: isoseq_human_liver_notfulllength/raw_data/liver.nfl.fasta
  isoseq_heart_fulllength: isoseq_human_heart_fulllength/raw_data/heart.flnc.fasta
  isoseq_heart_notfulllength: isoseq_human_heart_notfulllength/raw_data/heart.nfl.fasta

# directories to put outputs for each sample into - doesn't have to be the same directory as fastq_fn paths

basedirs: 
  isoseq_brain_fulllength: isoseq_human_brain_fulllength
  isoseq_brain_notfulllength: isoseq_human_brain_notfulllength
  isoseq_liver_fulllength: isoseq_human_liver_fulllength
  isoseq_liver_notfulllength: isoseq_human_liver_notfulllength
  isoseq_heart_fulllength: isoseq_human_heart_fulllength
  isoseq_heart_notfulllength: isoseq_human_heart_notfulllength

sequencing_type: isoseq

### REFERENCE PARAMETERS ###

genome_fasta_fn: /cluster/ggs_lab/mtparker/annotations/GRCh38/fasta/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa
chromsizes_fn: /cluster/ggs_lab/mtparker/annotations/GRCh38/fasta/Homo_sapiens.GRCh38.dna_sm.primary_assembly.chrom.sizes
transcriptome_fasta_fn: /cluster/ggs_lab/mtparker/annotations/GRCh38/fasta/Homo_sapiens.GRCh38.cdna.all.fa
annot_gtf: /cluster/ggs_lab/mtparker/annotations/GRCh38/gtf/Homo_sapiens.GRCh38.98.gtf
is_ensembl: True

### SIMULATEION PARAMETERS ###

yanosim_parameters:
  threads: 24
  random_seed: 101
  run_simulation: False
  simulate_three_prime_bias: False

### MAPPING PARAMETERS ###

minimap2_parameters:
  threads: 24
  max_intron_size: 200000
  junction_bonus: 12

### FILTERING PARAMETERS ###

2passtools_parameters:
  threads: 12
  jad_size_threshold: 4
  primary_junction_search_distance: 20
  canonical_motifs: 'GTAG|GCAG|ATAG'
  sequence_model_window_size: 128
  sequence_model_kfold: 6
  low_confidence_threshold: 0.1
  high_confidence_threshold: 0.6


### ASSEMBLY PARAMETERS ###

stringtie_parameters:
  threads: 4